export interface InterventionRequest {
  id: number,
  reference: string,
  customer: null,
  customerContactId: number,
  customerContact: string,
  technicianId: number,
  technician: null,
  priorityId: number,
  priority: string,
  contractTypeId: number,
  contractType: null,
  dateRequest: string,
  interventionReason: string[],
  cancellationReason: string[],
  statusId: number,
  status: string,
  interventionClassificationId: number,
  interventionClassification: string,
  expectedDateTEnd: string,
  emailToSendReport: string,
  periodId: number,
}
